# Generated by Django 4.1.3 on 2023-04-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGym', '0005_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
